# Generated by Django 4.2.4 on 2023-08-23 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('shift', models.IntegerField()),
                ('status', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('section', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Others'), (2, 'Pump Cashing'), (3, 'Motor Cashing'), (4, 'Jet Pump'), (5, 'Rotor'), (6, 'Finishing_PC'), (7, 'Finishing_MC'), (8, 'Impeller'), (9, 'Stator'), (10, 'Assy'), (11, 'Final Inspection'), (12, 'AIDA-DieCast')], default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Others'), (2, 'Pump Cashing'), (3, 'Motor Cashing'), (4, 'Jet Pump'), (5, 'Rotor'), (6, 'Finishing_PC'), (7, 'Finishing_MC'), (8, 'Impeller'), (9, 'Stator'), (10, 'Assy'), (11, 'Final Inspection'), (12, 'AIDA-DieCast')], default=1, null=True)),
                ('is_admin', models.BooleanField(default=False, verbose_name='Is_admin')),
                ('is_customer', models.BooleanField(default=False, verbose_name='Is_customer')),
                ('is_officer', models.BooleanField(default=False, verbose_name='Is_officer')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is_Active')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
