# Generated by Django 4.2.4 on 2023-09-17 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_customer',
            new_name='is_lead',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='is_officer',
            new_name='is_super',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_tech',
            field=models.BooleanField(default=False, verbose_name='Is_officer'),
        ),
    ]
