# Generated by Django 4.2.4 on 2023-09-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_is_customer_profile_is_lead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_lead',
            field=models.BooleanField(default=False, verbose_name='Is_lead'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_super',
            field=models.BooleanField(default=False, verbose_name='Is_super'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_tech',
            field=models.BooleanField(default=False, verbose_name='Is_tech'),
        ),
    ]
