# Generated by Django 4.2.4 on 2023-09-20 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_site_sub_name_alter_site_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Open_ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('site_name', models.TextField(max_length=50)),
                ('site_sub_name', models.TextField(default='', max_length=50)),
                ('site_section', models.TextField(default='', max_length=50)),
                ('time_issue', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
