# Generated by Django 4.2.4 on 2023-09-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_open_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='open_ticket',
            name='section_approved',
            field=models.BooleanField(default=False, verbose_name='approved'),
        ),
    ]
