# Generated by Django 4.2.4 on 2023-09-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_open_ticket_section_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='open_ticket',
            name='ticket_id',
            field=models.IntegerField(default=0),
        ),
    ]
