# Generated by Django 4.2.4 on 2023-09-26 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_open_ticket_ticket_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='open_ticket',
            name='section_approved',
        ),
    ]
