# Generated by Django 4.2.4 on 2023-09-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_open_ticket_section_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='open_ticket',
            name='description',
            field=models.TextField(default='', max_length=300),
        ),
    ]
