# Generated by Django 4.2.4 on 2023-09-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_open_ticket_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='open_ticket',
            name='site_section',
            field=models.PositiveSmallIntegerField(default=''),
        ),
    ]
