# Generated by Django 4.2.4 on 2023-09-26 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_open_ticket_site_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticket_stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('super_approve_time', models.DateField(default='')),
                ('pe_approved_time', models.DateField(default='')),
                ('pe_man_approved_time', models.DateField(default='')),
                ('complete', models.BooleanField(default=False)),
                ('ticket_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.open_ticket')),
            ],
        ),
    ]
