# Generated by Django 4.2.4 on 2023-09-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_ticket_stat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_stat',
            name='pe_approved_time',
            field=models.DateField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='ticket_stat',
            name='pe_man_approved_time',
            field=models.DateField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='ticket_stat',
            name='super_approve_time',
            field=models.DateField(default='', null=True),
        ),
    ]
