# Generated by Django 4.2.4 on 2023-09-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_ticket_stat_pe_approved_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='open_ticket',
            name='status',
            field=models.TextField(default='', max_length=50),
        ),
    ]
