# Generated by Django 4.0.8 on 2023-10-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_open_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_stat',
            name='pe_approved_time',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='ticket_stat',
            name='pe_man_approved_time',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='ticket_stat',
            name='super_approve_time',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
    ]
