# Generated by Django 4.0.8 on 2023-10-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_ticket_stat_pe_approved_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Downtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.IntegerField(default=0)),
                ('user_name', models.CharField(max_length=100)),
                ('site_name', models.TextField(max_length=50)),
                ('site_sub_name', models.TextField(default='', max_length=50)),
                ('site_section', models.PositiveSmallIntegerField(default='')),
                ('description', models.TextField(default='', max_length=300)),
                ('time_issue', models.DateTimeField(blank=True, default='', null=True)),
                ('time_finish', models.DateTimeField(blank=True, default='', null=True)),
                ('status', models.TextField(default='', max_length=50)),
            ],
        ),
    ]
