# Generated by Django 4.0.8 on 2023-10-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_downtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='downtime',
            name='analisis',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='downtime',
            name='spare_part',
            field=models.TextField(default='', max_length=300),
        ),
    ]
