# Generated by Django 4.0.8 on 2023-10-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_downtime_site_section_alter_downtime_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='downtime',
            name='reasons',
            field=models.TextField(blank=True, default='', max_length=50, null=True),
        ),
    ]
