# Generated by Django 4.2.4 on 2023-10-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_downtime_reasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='downtime',
            name='kyt_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
