# Generated by Django 4.2.4 on 2023-10-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_downtime_kyt_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket_stat',
            name='complete',
        ),
        migrations.AddField(
            model_name='downtime',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
