# Generated by Django 4.2.4 on 2023-10-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_remove_ticket_stat_complete_downtime_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downtime',
            name='kyt_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
