# Generated by Django 4.2.4 on 2023-10-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_downtime_kyt_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downtime',
            name='kyt_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
