# Generated by Django 4.2.4 on 2023-10-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_downtime_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='tech_action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.IntegerField(default=0)),
                ('pe_start', models.DateTimeField(blank=True, default='', null=True)),
                ('pe_finish', models.DateTimeField(blank=True, default='', null=True)),
                ('closed', models.DateTimeField(blank=True, default='', null=True)),
            ],
        ),
    ]
