# Generated by Django 4.2.4 on 2023-10-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_tech_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech_action',
            name='incharge',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
